Fixed ssl errors when importing transformers
RuntimeError: Failed to import transformers.data.data_collator because of the following error (look up to see its traceback):
libssl.so.10: cannot open shared object file: No such file or directory